name: Issue Label

on:
  issues:
    types: [opened]

jobs:
  issue-label:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Label to Issues Openend
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_ACTION_EXAMPLES_PAT }}
          script: |
            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               labels: ['triage']
            })
