name: Website Preview Deployment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  website-preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Install deps
      #   run: npm ci

      # - name: Build Website
      #   run: npm run build

      # - name: Get branch
      #   id: get-branch
      #   run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}

      - name: Check branch name
        id: get-branch
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      # - name: Deploy Website
      #   uses: dswistowski/surge-sh-action@v1
      #   with:
      #     domain: "github-action-examples.surge.sh"
      #     project: "dist"
      #     login: ${{ secrets.GH_ACTION_SURGE_LOGIN }}
      #     token: ${{ secrets.GH_ACTION_SURGE_TOKEN }}
